export const DepartmentMap: Record<string, string> = {
  JY: '生产经营管理科',
  FZ: '市场发展科',
  KG: '国土空间规划所',
  DC: '调查所',
  JC: '监测评价所',
  KS: '勘测设计所',
  HY: '航测遥感所',
  CH: '测绘地理信息所',
  DK: '地质勘察所',
  QT: '其他',
};

export const DepartmentMultiMap = [
  {
    id: 'GHZX001',
    departmentCode: 'DC',
    901: '调查所',
    902: '调查事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX002',
    departmentCode: 'HY',
    901: '航测遥感所',
    902: '航测遥感事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX003',
    departmentCode: 'KG',
    901: '国土空间规划所',
    902: '国土空间规划事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX004',
    departmentCode: 'KS',
    901: '勘测设计所',
    902: '勘测设计事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX005',
    departmentCode: 'CH',
    901: '测绘地理信息所',
    902: '测绘地理信息事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX006',
    departmentCode: 'JC',
    901: '监测评价所',
    902: '监测评价事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX007',
    departmentCode: 'DK',
    901: '地质勘察所',
    902: '地质勘察事业部',
    type: '生产部门',
  },
  {
    id: 'GHZX101',
    departmentCode: '',
    901: '办公室',
    902: '综合管理部',
    type: '管理部门',
  },
  {
    id: 'GHZX102',
    departmentCode: '',
    901: '财务资产管理科',
    902: '财务部',
    type: '管理部门',
  },
  {
    id: 'GHZX103',
    departmentCode: '',
    901: '人事科',
    902: '人力资源部',
    type: '管理部门',
  },
  {
    id: 'GHZX104',
    departmentCode: '',
    901: '科技信息科',
    902: '科技信息部',
    type: '管理部门',
  },
  {
    id: 'GHZX105',
    departmentCode: 'FZ',
    901: '市场发展科',
    902: '市场发展部',
    type: '管理部门',
  },
  {
    id: 'GHZX106',
    departmentCode: 'JY',
    901: '生产经营管理科',
    902: '生产经营管理部',
    type: '管理部门',
  },
  {
    id: 'GHZX107',
    departmentCode: '',
    901: '安全监督管理科',
    902: '安全监督管理部',
    type: '管理部门',
  },
  {
    id: '',
    departmentCode: 'QT',
    901: '其他',
    902: '其他',
    type: '',
  },
];
